### ISSUE TITLE
Docker typescript / run server bug

### ISSUE THREAD

**Issue by Stavrospanakakis** [ionian-uni-ieee/ieeesb-app#67]
I started docker with the command
```
$ docker-compose up -d --build --force-recreate
```
I typed "localhost:3000" on the browser but nothing happened.
When i run the command:
```
$ docker container logs docker_web_1  
```
The following error is shown:
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.22.1
$ react-scripts start
It looks like you're trying to use TypeScript but do not have typescript installed.
Please install typescript by running yarn add typescript.
If you are not trying to use TypeScript, please remove the tsconfig.json file from your package root (and any TypeScript files).

I tried to change the [web.Dockerfile](https://github.com/ionian-uni-ieee/ieeesb-app/blob/dev/build/docker/web.Dockerfile) by adding the following commands
```
RUN yarn add typescript
```
```
RUN npm install -g typescript
```
I started docker again but nothing happened. However, when i install nodejs, npm and yarn and typing the commands manually without docker it works.

**Comment by exapsy** [comment]
@Stavrospanakakis I think it's fixed with #68 . I reproduced it and its no longer reproducable.
The mistake was that the volumes in [docker-compose.override.yml web service](https://github.com/ionian-uni-ieee/ieeesb-app/pull/68/files#diff-8b011a8a600a0f33daff86b43f580556R11) where for some reason I yet not understand needs to be explicitely told that node_modules is a volume? I'll read more about it.
